# Generated by Django 4.1.7 on 2024-04-05 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='first_naame',
            new_name='first_name',
        ),
    ]
